language: android

android:
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

before_install:
  - adb shell || true # force to create the adbkey

install: docker run -d -e "ADBKEY=$(cat ~/.android/adbkey)" --privileged  --publish 5556:5556/tcp --publish 5555:5555/tcp braisgabin/android-emulator

after_install:
  - adb devices || true

script:
  - ./gradlew connectedCheck

cache:
  directories:
    - $HOME/.gradle
