language: java

dist: bionic

install:
  - . travis-bionic-android.sh

script:
  - java -version
  - javac -version
  - echo $ANDROID_HOME
  - echo $PATH
  - ./gradlew test

after_failure:
  - docker ps -a
  - docker logs device

notifications:
  email: false
