language: android

dist: bionic

install:
  - ls -la
  - ./travis-bionic-android.sh

script:
  - echo $ANDROID_HOME
  - echo $PATH
  - ./gradlew tasks
  - ./gradlew test

after_failure:
  - docker ps -a
  - docker logs device

notifications:
  email: false
