language: android

dist: bionic

before_install:
  - . travis-bionic-android.sh

install:
  - egrep -c '(vmx|svm)' /proc/cpuinfo
  - adb start-server # force to create the ~/.android/adbkey
  - docker run --name device -d -e "ADBKEY=$(cat ~/.android/adbkey)" --privileged --publish 5556:5556/tcp --publish 5555:5555/tcp braisgabin/android-emulator
  - android-wait-for-emulator

script:
  - java -version
  - javac -version
  - echo $ANDROID_HOME
  - echo $PATH
  - ./gradlew connectedCheck

after_failure:
  - docker ps -a
  - docker logs device

notifications:
  email: false
