language: java

dist: bionic

before_install:
  - . travis-bionic-android.sh

install:
  - egrep -qc '(vmx|svm)' /proc/cpuinfo # ensure that we have KVM enabled
  - adb start-server # force to create the ~/.android/adbkey
  - docker pull braisgabin/android-emulator >/dev/null # `docker pull -q` is not supported by travis
  - docker run --name device -d -e "ADBKEY=$(cat ~/.android/adbkey)" --privileged --publish 5556:5556/tcp --publish 5555:5555/tcp braisgabin/android-emulator
  - adb connect localhost:5555
  - ./wait-for-emulator
  - adb devices

script:
  - ./gradlew connectedCheck

after_script:
  - docker ps -a
  - docker logs device

notifications:
  email: false
