language: android

jdk:
  - oraclejdk9

install:
  - echo $ANDROID_HOME
  - curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > sdk.zip

before_script:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew connectedCheck

after_failure:
  - docker ps -a
  - docker logs device

cache:
  directories:
    - $HOME/.gradle
