language: java

dist: bionic

before_install:
  - . travis-bionic-android.sh
  - adb shell || true # force to create the adbkey

install: echo "no-op"

script:
  - java -version
  - javac -version
  - echo $ANDROID_HOME
  - echo $PATH
  - ./gradlew test

after_failure:
  - docker ps -a
  - docker logs device

notifications:
  email: false
