language: java

dist: bionic

jdk:
  - openjdk10

install:
  - export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee' # https://stackoverflow.com/a/51644855/842697
  - ANDROID_HOME=$HOME/android-sdk/
  - mkdir -p $ANDROID_HOME ~/.android/
  - curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > /tmp/sdk.zip
  - unzip -q -o /tmp/sdk.zip -d $ANDROID_HOME
  - touch ~/.android/repositories.cfg
  - mkdir -p $ANDROID_HOME/licenses
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3" "platform-tools"
  - PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools

script:
  - ./gradlew tasks
  - ./gradlew test

after_failure:
  - docker ps -a
  - docker logs device
